name: Auto Summry
on:
  issues:
    types: [opened]
jobs:
  addSummryComment:
    runs-on: ubuntu-latest
    name: Add Summry Comment
    steps:
      - uses: ericalexanderorg/github-actions/auto-summry@master
        env:
          SUMMRY_API_KEY: ${{ secrets.SUMMRY_API_KEY }}