name: Auto Summry
on:
  issues:
    types: [opened]
jobs:
  runs-on: ubuntu-latest
  addSummryComment:
    name: Add Summry Comment
    steps:
      - uses: ericalexanderorg/github-actions/auto-summry@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}